//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestroomManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist_Utility
    {
        public int ID { get; set; }
        public int U_ID { get; set; }
        public int ShiftId { get; set; }
        public bool IsDone { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ReadingDate { get; set; }
    
        public virtual ShiftMaster ShiftMaster { get; set; }
        public virtual Utility Utility { get; set; }
    }
}
